# Generated by Django 4.2.1 on 2023-06-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=50)),
                ('destination_ip', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=10)),
                ('packet_data', models.TextField()),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
