# Generated by Django 4.2.1 on 2023-08-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_sniffer', '0002_remove_packet_capture_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='classification',
            field=models.CharField(default='', max_length=50),
        ),
    ]
