# Generated by Django 4.2.1 on 2023-09-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_sniffer', '0003_packet_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='ip_destination',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='packet',
            name='ip_source',
            field=models.CharField(default='', max_length=50),
        ),
    ]
