# Generated by Django 4.2.1 on 2023-09-01 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_sniffer', '0004_packet_ip_destination_packet_ip_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 21, 38, 2, 156266, tzinfo=datetime.timezone.utc)),
        ),
    ]
